# Generated by Django 4.1.4 on 2022-12-30 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_alter_algorithm_secondary0_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_primary_stat_kr', models.CharField(max_length=50)),
                ('offense_secondary_stat_kr', models.CharField(blank=True, max_length=50)),
                ('stability_primary_stat_kr', models.CharField(max_length=50)),
                ('stability_secondary_stat_kr', models.CharField(blank=True, max_length=50)),
                ('special_primary_stat_kr', models.CharField(max_length=50)),
                ('special_secondary_stat_kr', models.CharField(blank=True, max_length=50)),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.doll')),
            ],
        ),
        migrations.RemoveField(
            model_name='combination',
            name='doll',
        ),
        migrations.RemoveField(
            model_name='combination',
            name='offense',
        ),
        migrations.RemoveField(
            model_name='combination',
            name='special',
        ),
        migrations.RemoveField(
            model_name='combination',
            name='stability',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='base',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='primary',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='secondary0',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='secondary1',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='name_kr',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='slot',
            field=models.CharField(choices=[('OFF', 'Offense'), ('STB', 'Stability'), ('SPC', 'Special')], default='OFF', max_length=3),
        ),
        migrations.DeleteModel(
            name='AlgorithmBase',
        ),
        migrations.DeleteModel(
            name='Combination',
        ),
        migrations.DeleteModel(
            name='PrimaryStat',
        ),
        migrations.DeleteModel(
            name='SecondaryStat',
        ),
        migrations.AddField(
            model_name='recommendedset',
            name='offense_algorithm',
            field=models.ForeignKey(limit_choices_to={'slot': 'OFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='algorithm.algorithm'),
        ),
        migrations.AddField(
            model_name='recommendedset',
            name='special_algorithm',
            field=models.ForeignKey(limit_choices_to={'slot': 'SPC'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='algorithm.algorithm'),
        ),
        migrations.AddField(
            model_name='recommendedset',
            name='stability_algorithm',
            field=models.ForeignKey(limit_choices_to={'slot': 'STB'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='algorithm.algorithm'),
        ),
    ]
