# Generated by Django 4.1.4 on 2022-12-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_recommendedset_remove_combination_doll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='name_kr',
            field=models.CharField(max_length=30),
        ),
    ]
