# Generated by Django 4.1.4 on 2022-12-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0004_alter_algorithm_name_alter_algorithm_name_kr'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='is_useless',
            field=models.BooleanField(default=False),
        ),
    ]
