# Generated by Django 4.1.5 on 2023-01-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0005_algorithm_is_useless'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kr', models.CharField(max_length=50)),
                ('alias_kr', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='recommendedset',
            name='offense_primary_stats',
            field=models.ManyToManyField(to='algorithm.stat'),
        ),
    ]
