# Generated by Django 4.1.5 on 2023-01-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0006_stat_recommendedset_offense_primary_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedset',
            name='special_primary_stats',
            field=models.ManyToManyField(related_name='+', to='algorithm.stat'),
        ),
        migrations.AddField(
            model_name='recommendedset',
            name='stability_primary_stats',
            field=models.ManyToManyField(related_name='+', to='algorithm.stat'),
        ),
        migrations.AlterField(
            model_name='recommendedset',
            name='offense_primary_stats',
            field=models.ManyToManyField(related_name='+', to='algorithm.stat'),
        ),
    ]
