# Generated by Django 4.1.5 on 2023-01-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0007_recommendedset_special_primary_stats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['name_kr']},
        ),
        migrations.RemoveField(
            model_name='recommendedset',
            name='offense_primary_stat_kr',
        ),
        migrations.RemoveField(
            model_name='recommendedset',
            name='offense_secondary_stat_kr',
        ),
        migrations.RemoveField(
            model_name='recommendedset',
            name='special_primary_stat_kr',
        ),
        migrations.RemoveField(
            model_name='recommendedset',
            name='special_secondary_stat_kr',
        ),
        migrations.RemoveField(
            model_name='recommendedset',
            name='stability_primary_stat_kr',
        ),
        migrations.RemoveField(
            model_name='recommendedset',
            name='stability_secondary_stat_kr',
        ),
        migrations.AddField(
            model_name='recommendedset',
            name='offense_secondary_stats',
            field=models.ManyToManyField(related_name='+', to='algorithm.stat'),
        ),
        migrations.AddField(
            model_name='recommendedset',
            name='special_secondary_stats',
            field=models.ManyToManyField(related_name='+', to='algorithm.stat'),
        ),
        migrations.AddField(
            model_name='recommendedset',
            name='stability_secondary_stats',
            field=models.ManyToManyField(related_name='+', to='algorithm.stat'),
        ),
    ]
