# Generated by Django 4.1.4 on 2023-01-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0009_alter_algorithm_options_useless'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'ordering': ['slot', 'name_kr']},
        ),
        migrations.AlterField(
            model_name='useless',
            name='stats',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='algorithm.stat'),
        ),
    ]
