# Generated by Django 4.1.4 on 2023-01-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0010_alter_algorithm_options_alter_useless_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useless',
            name='stats',
            field=models.ManyToManyField(blank=True, related_name='+', to='algorithm.stat'),
        ),
    ]
